version: '3'

services:
  ##############################
  ##          한움페이         ##
  ##############################
  hanum-pay:
    build: ./services/hanum-pay
    restart: always
    depends_on:
      - db
      - cache
    ports:
      - 5510:80
    networks:
      - default
      - internal
  ##############################
  ##     한움페이 대시보드     ##
  ##############################
  hanum-pay-dashboard:
    build: ./services/hanum-pay-dashboard
    restart: always
    ports:
      - 5512:80
    networks:
      - default
      - internal

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./services/nginx/conf.d/:/etc/nginx/conf.d/
      - ./services/nginx/www/:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - hanum-pay
      - hanum-pay-dashboard

  db:
    image: mariadb:10.11
    restart: always
    env_file:
      - ./.config/mysql.env
    volumes:
      - ./.data/mysql/:/var/lib/mysql
      # 서순주의
      - ./services/hanum-pay/Database/hanum/:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306
    networks:
      - default
      - internal
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-connections=344

  cache:
    image: redis:4
    restart: always
    volumes:
      - .data/redis:/data
    ports:
      - 6380:6379
    networks:
      - default
      - internal

networks:
  default:
  internal:
    internal: true
