version: '3'

services:
  ##############################
  ##          한움페이         ##
  ##############################
  hanum-pay:
    build: ./services/hanum-pay
    restart: always
    depends_on:
      - db
      - cache
      - auth-grpc
    ports:
      - 5510:80
    networks:
      - default
      - internal
    environment:
      - TZ=Asia/Seoul

  ##############################
  ##     한움페이 대시보드     ##
  ##############################
  hanum-pay-dashboard:
    build: ./services/hanum-pay-dashboard
    restart: always
    ports:
      - 5512:80
    networks:
      - default
      - internal
    environment:
      - TZ=Asia/Seoul

  ##############################
  ##          인증서버          ##
  ##############################
  auth:
    build: ./services/auth
    restart: always
    environment:
      - SERVER_TYPE=HTTP
      - TZ=Asia/Seoul
    depends_on:
      - db
      - cache
    ports:
      - 5511:80
    networks:
      - default
      - internal

  ##############################
  ##        한세어울림한마당       ##
  ##############################

  festival:
    build: ./services/festival
    restart: always
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./.config/festival.env
    depends_on:
      - db
      - auth-grpc
    ports:
      - 5514:80
    networks:
      - default
      - internal

  ##############################
  ##   인증 마이크로서비스 GRPC    ##
  ##############################
  auth-grpc:
    build: ./services/auth
    restart: always
    environment:
      - SERVER_TYPE=GRPC
      - TZ=Asia/Seoul
    ports:
      - 50051:50051
    depends_on:
      - db
      - cache

  ##############################
  ##          정보서버          ##
  ##############################
  info:
    build: ./services/info
    restart: always
    ports:
      - 5513:80
    networks:
      - default
      - internal
    depends_on:
      - auth-grpc
    environment:
      - TZ=Asia/Seoul

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./services/nginx/conf.d/:/etc/nginx/conf.d/
      - ./services/nginx/www/:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - hanum-pay
      - hanum-pay-dashboard
      - auth
      - festival
    environment:
      - TZ=Asia/Seoul

  ##############################
  ##        한움페이 충전봇       ##
  ##############################
  pay-bot:
    build: ./services/pay-bot
    restart: always
    env_file:
      - ./.config/pay-bot.env
    depends_on:
      - db
    environment:
      - TZ=Asia/Seoul

  db:
    image: mariadb:10.11
    restart: always
    env_file:
      - ./.config/mysql.env
    volumes:
      - ./.data/mysql/:/var/lib/mysql
      # 서순주의
      - ./services/hanum-pay/Database/hanum/:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306
    networks:
      - default
      - internal
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-connections=344
      - --ft-min-word-len=1
      - --innodb-ft-min-token-size=1
      - --ft-stopword-file=""

  cache:
    image: redis:4
    restart: always
    volumes:
      - .data/redis:/data
    ports:
      - 6380:6379
    networks:
      - default
      - internal
    environment:
      - TZ=Asia/Seoul

networks:
  default:
  internal:
    internal: true
